### ISSUE TITLE
head_mover sometimes dies randomly

### ISSUE THREAD

**Issue by timonegk** [bit-bots/bitbots_behavior#324] opened 2023-07-06 13:42 UTC
The head mover sometimes dies randomly with a segmentation fault. There is no helpful error message, so we will have to investigate some more.
I think it said "Looking at point" very often, then "Received goal request" once, then "Looking at point" a few times, then it died.

When the head mover is dead, the behavior is not doing anything because it is waiting for the head mover service.

**Comment by jaagut** [comment] 2023-11-24 16:09
Will close this now, as we did not reproduce this behavior since and the code has been refactored, which might have resolved this issue.

**Closed by jaagut** 2023-11-24 16:09 UTC
Labels: bug
