### ISSUE TITLE
Throwin: Keep distance to ball from inside the field

### ISSUE THREAD

**Issue by johagge** [bit-bots/bitbots_behavior#178] opened 2021-06-06 12:16 UTC
## Is your feature request related to a problem? Please describe.

Currently when we are outside the field and a throwin is awarded to the other team we will walk 2 meters away from the ball to keep a safe distance. If we are currently outside the field, we will walk further outside the field to keep our distance. 
[Video of this behavior](https://streamable.com/w9zgt7)

## Describe the solution you'd like

I think instead of only considering the distance to the ball, we should ensure our target position is inside the field.

**Comment by Flova** [comment] 2021-06-06 12:23
Closing because its a duplicate of #165

**Closed by Flova** 2021-06-06 12:23 UTC
Labels: enhancement
